version: '3'
services:
  database:
    image: mysql:5.7
    restart: always
    container_name: database.errordetect
    ports:
      - "3377:3306"
    networks:
      errordetectionnetwork:
        aliases:
          - database_mysql
    environment:
      MYSQL_DATABASE: "errordetection"
      MYSQL_ROOT_PASSWORD: "root123"
  adminer:
    image: adminer:latest
    restart: always
    container_name: adminer.errordetect
    ports:
      - "9888:8080"
    networks:
      errordetectionnetwork:
        aliases:
          - adminer_controller
networks:
  errordetectionnetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.28.0/24
