# Generated by Django 2.0 on 2019-06-28 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('device_limit', models.IntegerField(blank=True)),
                ('expire_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CorporationIssues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('finish_date', models.DateTimeField(null=True)),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corp', to='detect.Corporation')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc_no', models.CharField(max_length=11)),
                ('facility', models.TextField(blank=True)),
                ('facility_location_lat', models.FloatField(blank=True, default=0)),
                ('facility_location_lon', models.FloatField(blank=True, default=0)),
                ('dev_uuid', models.CharField(blank=True, max_length=256)),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin1', to='detect.Corporation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerFacilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_tag', models.CharField(max_length=256)),
                ('facility_location_lat', models.FloatField(blank=True, default=0)),
                ('facility_location_lon', models.FloatField(blank=True, default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_facility', to='detect.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('issue_emergency', models.IntegerField(blank=True)),
                ('is_done', models.BooleanField(default=False)),
                ('is_attached', models.BooleanField(default=False)),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detect.Corporation')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='detect.Customer')),
                ('customer_fac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custfacility', to='detect.CustomerFacilities')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc_no', models.CharField(max_length=11)),
                ('dev_uuid', models.CharField(blank=True, max_length=256)),
                ('is_manager', models.BooleanField(default=False)),
                ('last_location_lat', models.FloatField(blank=True, default=0)),
                ('last_location_lon', models.FloatField(blank=True, default=0)),
                ('is_busy', models.BooleanField(default=False)),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detect.Corporation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=256)),
                ('price', models.FloatField(blank=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detect.Corporation')),
            ],
        ),
        migrations.CreateModel(
            name='UsedMaterials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detect.Corporation')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detect.Materials')),
            ],
        ),
        migrations.AddField(
            model_name='corporationissues',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='detect.Employee'),
        ),
        migrations.AddField(
            model_name='corporationissues',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue', to='detect.CustomerIssue'),
        ),
        migrations.AddField(
            model_name='corporationissues',
            name='used_materials',
            field=models.ManyToManyField(blank=True, to='detect.UsedMaterials'),
        ),
    ]
