# Generated by Django 2.0 on 2019-07-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0002_corporationcustomerdebts'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedmaterials',
            name='mat_name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usedmaterials',
            name='mat_price',
            field=models.FloatField(blank=True, default=0.0),
            preserve_default=False,
        ),
    ]
