# Generated by Django 2.0 on 2019-07-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0003_auto_20190702_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporationcustomerdebts',
            name='corp',
        ),
        migrations.RemoveField(
            model_name='corporationcustomerdebts',
            name='issue',
        ),
        migrations.AddField(
            model_name='usedmaterials',
            name='payed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='CorporationCustomerDebts',
        ),
    ]
