# Generated by Django 2.0 on 2019-07-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0004_auto_20190703_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporationissues',
            name='employee_refuse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='corporationissues',
            name='refuse_description',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
