# Generated by Django 2.0 on 2019-07-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0005_auto_20190704_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_passive',
            field=models.BooleanField(default=False),
        ),
    ]
