# Generated by Django 2.0 on 2019-07-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0006_employee_is_passive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_passive',
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
