# Generated by Django 2.0 on 2019-07-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0007_auto_20190707_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='payed',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='unpayed',
            field=models.FloatField(default=0),
        ),
    ]
