# Generated by Django 2.0 on 2019-07-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0009_remove_usedmaterials_payed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedmaterials',
            name='count',
            field=models.FloatField(blank=True),
        ),
    ]
