# Generated by Django 2.0 on 2019-07-16 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0010_auto_20190714_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDebtHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payed_date', models.DateTimeField(auto_now=True)),
                ('payed_amount', models.FloatField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_debt', to='detect.Customer')),
            ],
        ),
    ]
