# Generated by Django 2.0 on 2019-07-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0011_customerdebthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='limit',
            field=models.FloatField(default=0),
        ),
    ]
